### ISSUE TITLE
infografiacharly

### ISSUE THREAD

**Issue by Sandoval6** [SistemasTecTlaxiaco/actividad-1-infografia-Sandoval6#2]
[Infografía_Charly Joshua Sandoval Hernández.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-Sandoval6/files/12490065/Infografia_Charly.Joshua.Sandoval.Hernandez.pdf)

**Comment by ToniDepp** [comment]
Redacción y ortografía: Impecable 3 puntos de 3 puntos
Exposición de ideas centrales: Buen aprovechamiento de los recursos 3 puntos de 3 puntos
Organización de la información: Lo indispensable 3 puntos de 3 puntos
Uso de imágenes y colores: Buen manejo de los colores 3 puntos de 3 puntos
Presentación visual: Buen diseño 3 puntos de 3 puntos
Referencias: Carece del formato, pero es útil 2 puntos de 2 puntos 
Presentación: 3 puntos de 3 puntos
Calificación: 20/ 20
Calificado por: Eduardo Tomas

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
